### ISSUE TITLE
Get v8 library is failed...

### ISSUE THREAD

**Issue by CairoLee** [Borf/browedit#2]
@Borf  Hi sir. 
I try to running browedit\externals\v8\get.bat , but it's failed.
look like the http://v8.borf.info server is down..

![qq20160513-0](https://cloud.githubusercontent.com/assets/4458917/15238238/52559c76-1908-11e6-8a4d-40e2802ee9d7.png)

could you fix it please? thank you sir.

**Comment by Borf** [comment]
Hi there

it should be back up, misconfigured my apache

Borf

**Comment by CairoLee** [comment]
@Borf It's work now, thank you! XD
